site_name: DALIA Audio Engine
site_description: A real-time, low-latency, data-oriented audio engine for games and game engines written in C++.
site_author: Arvid Wahlgren
repo_url: https://github.com/amHumminG/dalia
repo_name: amHumminG/dalia

theme:
  name: material
  features:
    - navigation.tabs
    - navigation.sections
    - navigation.top
    - search.suggest
    - search.highlight
    - content.code.copy
  palette:
    - scheme: slate
      primary: blue
      accent: blue

# Sidebar nav menu
nav:
  - Introduction: index.md

markdown_extensions:
  - admonition
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences