site_name: DALIA Engine
site_description: A real-time, low-latency, data-oriented audio engine for games and game engines written in C++.
site_author: Arvid Wahlgren
repo_url: https://github.com/amHumminG/dalia
repo_name: amHumminG/dalia

theme:
  name: material

  logo: assets/dalia_icon_transparent.png
  favicon: assets/dalia_icon_transparent.png

  font:
    text: Inter
    code: JetBrains Mono

  features:
    - navigation.tabs
    - navigation.sections
    - navigation.top
    - search.suggest
    - search.highlight
    - content.code.copy

  palette:
    - scheme: slate
      primary: black
      accent: blue

# Sidebar nav menu
nav:
  - Home: index.md
  - Getting Started: getting-started.md
  - Architecture: architecture.md
  - Guide:
      - Asset Management: guide/asset-management.md
      - Mixing & Routing: guide/mixing.md
      - Playback Control: guide/playback.md
      - Spatialization: guide/spatialization.md
  - API Reference:
      - Classes & Structs: api/annotated.md
      - NameSpaces: api/namespaces.md
      - Files: api/files.md

markdown_extensions:
  - attr_list
  - admonition
  - toc:
      permalink: true
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg

extra_css:
  - stylesheets/extra.css

plugins:
  - search
  - mkdoxy:
      projects:
        api:
          src-dirs: engine/include/dalia
          full-doc: True
          doxy-cfg:
            RECURSIVE: True
            EXTRACT_ALL: True
