name: Build and Deploy Documentation

# Only trigger on pushes to main
on:
  push:
    branches:
      - main

# Action has permission to write to gh pages
permissions:
  contents: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Doxygen
        run: sudo apt-get update && sudo apt-get install -y doxygen

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.x

      - name: Install MkDocs and MkDoxy
        run: |
          pip install mkdocs-material 
          pip install mkdoxy

      - name: Build and Deploy to GitHub Pages
        run: mkdocs gh-deploy --force